version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019" -A x64

build:
  project: build/lab04.sln
  verbosity: minimal

test_script:
  - cd build
  - .\Debug\hello_world_application\hello_world.exe
  - echo 1 -3 2 | .\Debug\solver_application\solver.exe
